import * as alt from "alt-client";
import { z } from "zod";

// export const baseObject = z.custom<alt.BaseObject>((val) => val instanceof alt.BaseObject);
// export const virtualEntityGroup = z.custom<alt.VirtualEntityGroup>((val) => val instanceof alt.VirtualEntityGroup);
// export const virtualEntity = z.custom<alt.VirtualEntity>((val) => val instanceof alt.VirtualEntity);
// export const audio = z.custom<alt.Audio>((val) => val instanceof alt.Audio);
// export const worldObject = z.custom<alt.WorldObject>((val) => val instanceof alt.WorldObject);
// export const checkpoint = z.custom<alt.Checkpoint>((val) => val instanceof alt.Checkpoint);
// export const entity = z.custom<alt.Entity>((val) => val instanceof alt.Entity);
// export const player = z.custom<alt.Player>((val) => val instanceof alt.Player);
// export const localPlayer = z.custom<alt.LocalPlayer>((val) => val instanceof alt.LocalPlayer);
// export const vehicle = z.custom<alt.Vehicle>((val) => val instanceof alt.Vehicle);
// export const webview = z.custom<alt.WebView>((val) => val instanceof alt.WebView);
// export const worker = z.custom<alt.Worker>((val) => val instanceof alt.Worker);
// export const blip = z.custom<alt.Blip>((val) => val instanceof alt.Blip);
// export const areaBlip = z.custom<alt.AreaBlip>((val) => val instanceof alt.AreaBlip);
// export const radiusBlip = z.custom<alt.RadiusBlip>((val) => val instanceof alt.RadiusBlip);
// export const pointBlip = z.custom<alt.PointBlip>((val) => val instanceof alt.PointBlip);
// export const handlingData = z.custom<alt.HandlingData>((val) => val instanceof alt.HandlingData);
// export const mapZoomData = z.custom<alt.MapZoomData>((val) => val instanceof alt.MapZoomData);

// export const localStorage = z.custom<alt.LocalStorage>((val) => val instanceof alt.LocalStorage);
// export const memoryBuffer = z.custom<alt.MemoryBuffer>((val) => val instanceof alt.MemoryBuffer);
// export const discord = z.custom<alt.Discord>((val) => val instanceof alt.Discord);
// export const voice = z.custom<alt.Voice>((val) => val instanceof alt.Voice);
// export const webSocketClient = z.custom<alt.WebSocketClient>((val) => val instanceof alt.WebSocketClient);
// export const httpClient = z.custom<alt.HttpClient>((val) => val instanceof alt.HttpClient);
// export const profiler = z.custom<alt.Profiler>((val) => val instanceof alt.Profiler);
// export const rmlDocument = z.custom<alt.RmlDocument>((val) => val instanceof alt.RmlDocument);
// export const rmlElement = z.custom<alt.RmlElement>((val) => val instanceof alt.RmlElement);
// export const utils = z.custom<alt.Utils>((val) => val instanceof alt.Utils);
// export const focusData = z.custom<alt.FocusData>((val) => val instanceof alt.FocusData);
// export const weaponData = z.custom<alt.WeaponData>((val) => val instanceof alt.WeaponData);
// export const object = z.custom<alt.Object>((val) => val instanceof alt.Object);
// export const weaponObject = z.custom<alt.WeaponObject>((val) => val instanceof alt.WeaponObject);
// export const networkObject = z.custom<alt.NetworkObject>((val) => val instanceof alt.NetworkObject);
// export const ped = z.custom<alt.Ped>((val) => val instanceof alt.Ped);
// export const audioFilter = z.custom<alt.AudioFilter>((val) => val instanceof alt.AudioFilter);
// export const marker = z.custom<alt.Marker>((val) => val instanceof alt.Marker);

// export const colshape = z.custom<alt.Colshape>((val) => val instanceof alt.Colshape);
// export const colshapeCylinder = z.custom<alt.ColshapeCylinder>((val) => val instanceof alt.ColshapeCylinder);
// export const colshapeSphere = z.custom<alt.ColshapeSphere>((val) => val instanceof alt.ColshapeSphere);
// export const colshapeCircle = z.custom<alt.ColshapeCircle>((val) => val instanceof alt.ColshapeCircle);
// export const colshapeCuboid = z.custom<alt.ColshapeCuboid>((val) => val instanceof alt.ColshapeCuboid);
// export const colshapeRectangle = z.custom<alt.ColshapeRectangle>((val) => val instanceof alt.ColshapeRectangle);
// export const colshapePolygon = z.custom<alt.ColshapePolygon>((val) => val instanceof alt.ColshapePolygon);
// export const textLabel = z.custom<alt.TextLabel>((val) => val instanceof alt.TextLabel);
// export const localVehicle = z.custom<alt.LocalVehicle>((val) => val instanceof alt.LocalVehicle);
// export const localPed = z.custom<alt.LocalPed>((val) => val instanceof alt.LocalPed);
// export const font = z.custom<alt.Font>((val) => val instanceof alt.Font);
// export const vector3 = z.custom<alt.Vector3>((val) => val instanceof alt.Vector3);
// export const vector2 = z.custom<alt.Vector2>((val) => val instanceof alt.Vector2);
// export const quaternion = z.custom<alt.Quaternion>((val) => val instanceof alt.Quaternion);
// export const rgba = z.custom<alt.RGBA>((val) => val instanceof alt.RGBA);
// export const file = z.custom<alt.File>((val) => val instanceof alt.File);
// export const resource = z.custom<alt.Resource>((val) => val instanceof alt.Resource);

export const baseObject = z.custom<alt.BaseObject>(() => true);
export const virtualEntityGroup = z.custom<alt.VirtualEntityGroup>(() => true);
export const virtualEntity = z.custom<alt.VirtualEntity>(() => true);
export const audio = z.custom<alt.Audio>(() => true);
export const worldObject = z.custom<alt.WorldObject>(() => true);
export const checkpoint = z.custom<alt.Checkpoint>(() => true);
export const entity = z.custom<alt.Entity>(() => true);
export const player = z.custom<alt.Player>(() => true);
export const localPlayer = z.custom<alt.LocalPlayer>(() => true);
export const vehicle = z.custom<alt.Vehicle>(() => true);
export const webview = z.custom<alt.WebView>(() => true);
export const worker = z.custom<alt.Worker>(() => true);
export const blip = z.custom<alt.Blip>(() => true);
export const areaBlip = z.custom<alt.AreaBlip>(() => true);
export const radiusBlip = z.custom<alt.RadiusBlip>(() => true);
export const pointBlip = z.custom<alt.PointBlip>(() => true);
export const handlingData = z.custom<alt.HandlingData>(() => true);
export const mapZoomData = z.custom<alt.MapZoomData>(() => true);

export const localStorage = z.custom<alt.LocalStorage>(() => true);
export const memoryBuffer = z.custom<alt.MemoryBuffer>(() => true);
export const discord = z.custom<alt.Discord>(() => true);
export const voice = z.custom<alt.Voice>(() => true);
export const webSocketClient = z.custom<alt.WebSocketClient>(() => true);
export const httpClient = z.custom<alt.HttpClient>(() => true);
export const profiler = z.custom<alt.Profiler>(() => true);
export const rmlDocument = z.custom<alt.RmlDocument>(() => true);
export const rmlElement = z.custom<alt.RmlElement>(() => true);
export const utils = z.custom<alt.Utils>(() => true);
export const focusData = z.custom<alt.FocusData>(() => true);
export const weaponData = z.custom<alt.WeaponData>(() => true);
export const object = z.custom<alt.Object>(() => true);
export const weaponObject = z.custom<alt.WeaponObject>(() => true);
export const networkObject = z.custom<alt.NetworkObject>(() => true);
export const ped = z.custom<alt.Ped>(() => true);
export const audioFilter = z.custom<alt.AudioFilter>(() => true);
export const marker = z.custom<alt.Marker>(() => true);

export const colshape = z.custom<alt.Colshape>(() => true);
export const colshapeCylinder = z.custom<alt.ColshapeCylinder>(() => true);
export const colshapeSphere = z.custom<alt.ColshapeSphere>(() => true);
export const colshapeCircle = z.custom<alt.ColshapeCircle>(() => true);
export const colshapeCuboid = z.custom<alt.ColshapeCuboid>(() => true);
export const colshapeRectangle = z.custom<alt.ColshapeRectangle>(() => true);
export const colshapePolygon = z.custom<alt.ColshapePolygon>(() => true);
export const textLabel = z.custom<alt.TextLabel>(() => true);
export const localVehicle = z.custom<alt.LocalVehicle>(() => true);
export const localPed = z.custom<alt.LocalPed>(() => true);
export const font = z.custom<alt.Font>(() => true);
export const vector3 = z.custom<alt.Vector3>(() => true);
export const vector2 = z.custom<alt.Vector2>(() => true);
export const quaternion = z.custom<alt.Quaternion>(() => true);
export const rgba = z.custom<alt.RGBA>(() => true);
export const file = z.custom<alt.File>(() => true);
export const resource = z.custom<alt.Resource>(() => true);
